import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./components/Navber/ResponsiveNav";
import Footer from "./components/Footer/Footer";

const poppins = Poppins(
  {weight:['400','500','600','700','800'],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "aTech |  Build your Dreams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ResponsiveNav></ResponsiveNav>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
